database_url: postgres://prod-server:5432/app
api_key: sk-prod-12345-secret
oidc_client_id: prod-client-id-12345
oidc_client_secret: super-secret-key-67890

new_production_secret: super-secret-key-123
database_password: prod-db-password-456
oidc_client_secret: updated-secret-789
